// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKnomg6mA7ESBEts3wIkAgoGEK5Gqzqg',
    appId: '1:850532143462:web:521c1dcdbf559480a238a7',
    messagingSenderId: '850532143462',
    projectId: 'project688688',
    authDomain: 'project688688.firebaseapp.com',
    storageBucket: 'project688688.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg15U28XAqxLgQe4K7thWtzA-H9H7hMv4',
    appId: '1:850532143462:android:f0378c0a06be0d83a238a7',
    messagingSenderId: '850532143462',
    projectId: 'project688688',
    storageBucket: 'project688688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGe2rUg97X_S5djHvfy208dtfGjf3eco',
    appId: '1:850532143462:ios:1e5822da6f1b51f7a238a7',
    messagingSenderId: '850532143462',
    projectId: 'project688688',
    storageBucket: 'project688688.appspot.com',
    iosBundleId: 'com.example.todoflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeGe2rUg97X_S5djHvfy208dtfGjf3eco',
    appId: '1:850532143462:ios:1e5822da6f1b51f7a238a7',
    messagingSenderId: '850532143462',
    projectId: 'project688688',
    storageBucket: 'project688688.appspot.com',
    iosBundleId: 'com.example.todoflutter',
  );
}
